flask/src/app.py
from flask import Flask, render_template
from flask_cors import CORS
from blueprints.autenticacion import autenticacion_bp
from blueprints.tareas import tareas_bp

# Instancia de la aplicacón
app = Flask(__name__, static_folder='static')
app.secret_key = 'secret key'


# Cross-Origin Resource Sharing - Compartir recursos entre diferentes orígenes
CORS(app, resources={r'/*': {'origins': '*'}})

# Rutas
@app.route('/')
def index():
    return render_template('autenticacion/login.html')

app.register_blueprint(autenticacion_bp)
app.register_blueprint(tareas_bp)

# Se coloca la apliacion en modo de escucha
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=3000, debug=True)

flask/src/blueprints/autenticacion.py
from flask import Blueprint, request, render_template, flash
from app_state import usuarios, tareas

autenticacion_bp = Blueprint(
    'autenticacion_bp',
    __name__,
    url_prefix='/autenticacion'
)


@autenticacion_bp.route('/registro', methods=['GET', 'POST'])
def registro():
    if request.method == 'GET':
        return render_template('autenticacion/registro.html')
    else:
        usuarios.append(request.form)
        return render_template('autenticacion/login.html')
        

@autenticacion_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('autenticacion/login.html')
    else:
        nombre = request.form['nombre']
        contrasenia = request.form['contrasenia']
        for usuario in usuarios:
            if nombre == usuario['nombre'] and contrasenia == usuario['contrasenia']:
                return render_template('tareas/crear_tarea.html', usuario = usuario)
            else:
                return render_template('autenticacion/login.html')

flask/src/blueprints/tareas.py
from flask import Blueprint, request, render_template, redirect
from app_state import usuarios, tareas

tareas_bp = Blueprint(
    'tareas_bp',
    __name__,
    url_prefix='/tareas'
)


@tareas_bp.route('/agregar_tarea', methods=['POST'])
def agregar_tarea():
    tarea = request.form['tarea']
    tareas.append(tarea)
    return redirect(request.url)

flask/src/templates/autenticacion/login.html
{% extends "index.html" %}

{% block styles %}
  <link rel="stylesheet" href="{{url_for('static', filename='css/autenticacion/login.css')}}" type="text/css" />
{% endblock %}

{% block content %}
  <form id="form" method="POST" action="{{url_for('autenticacion_bp.login')}}">
    <h1>Login</h1>
    <div class="form-field">
      <label>Nombre: </label>
      <input name="nombre" type="text" placeholder="nombre" />
    </div>
    <div class="form-field">
      <label>Contraseña: </label>
      <input name="contrasenia" type="text" placeholder="contraseña" />
    </div>
    <button type="submit" class="ingresoButton">Ingresar</button>
    <a href="{{url_for('autenticacion_bp.registro')}}">Registrarse</a>
  </form>
{% endblock %}

flask/src/templates/autenticacion/registro.html
{% extends "index.html" %}

{% block styles %}
  <link rel="stylesheet" href="{{url_for('static', filename='css/autenticacion/registro.css')}}" type="text/css" />
{% endblock %}

{% block content %}
  <form id="form" method="POST" action="{{url_for('autenticacion_bp.registro')}}">
    <h1>Registro</h1>
    <div class="form-field">
      <label>Nombre: </label>
      <input name="nombre" type="text" placeholder="nombre" />
    </div>
    <div class="form-field">
      <label>Apellido: </label>
      <input name="apellido" type="text" placeholder="correo" />
    </div>
    <div class="form-field">
      <label>Fecha Nacimiento: </label>
      <input name="fecha_nacimiento" type="date" placeholder="contraseña" />
    </div>
    <div class="form-field">
      <label>Sexo: </label>
      <select name="sexo">
        <option vale="M">M</option>
        <option value="F">F</option>
      </select>
    </div>
    <div class="form-field">
      <label>Nombre de usuario: </label>
      <input name="alias" type="text" placeholder="alias" />
    </div>
    <div class="form-field">
      <label>Contrasenia: </label>
      <input name="contrasenia" type="text" placeholder="contraseña" />
    </div>
    <div class="form-field">
      <label>Telefono: </label>
      <input name="telefono" type="text" placeholder="telefono" />
    </div>
    <button type="submit" class="ingresoButton">Registrarse</button>
    <a href="{{url_for('autenticacion_bp.login')}}">Login</a>
  </form>
{% endblock %}

flask/src/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title> IPC1 </title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/base.css')}}" type="text/css" />
    {% block styles %}{% endblock %}
  </head>
  <body> 
    {% block content %}{% endblock %}
  </body>
</html>

flask/src/templates/layout/menu.html
{% extends "index.html" %}


{% block content %}
  {% with usuario=usuario %}
    {% include 'layout/navbar.html' %}
  {% endwith %}
  {% block menu_content %} {% endblock %}
{% endblock %}

flask/src/templates/layout/navbar.html
{% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/layout/navbar.css')}}" type="text/css" />
{% endblock %}

<nav>
    <ul>
        <li>Tareas</li>
        <li>Perfil</li>
        <li class="ultimo">{{usuario['nombre']}}</li>
    </ul>
</nav>

flask/src/templates/tareas/crear_tarea.html
{% extends "/layout/menu.html" %}

{% block styles %}
    <link rel="stylesheet" href="{{url_for('static', filename='css/tareas/crear_tabla.css')}}" type="text/css" />
{% endblock %}

{% block menu_content %}
    <div class="contenedor">
        <h1>Ingrese una tarea:</h1>
        <form method="POST"  action="{{ url_for('tareas_bp.agregar_tarea') }}">
            <input type="text" name="tarea"></input>
            <button type="submit"> Agregar Tarea </button>
        </form>
        <table>
            {% for tarea in usuario['tareas'] %}
                <tr>
                    <td>{{tarea}}</td>
                    <td>
                        <button> Eliminar </button>
                    </td>
                </tr>
            {% endfor %}
        </table>
    <div>
{% endblock %}